<h3>스프링 기반 REST API 개발</h3>
<hr/>
<h5>예외 테스트</h5>

AccountService를 구현할 때 DB에서 account를 읽어오는 loadUserByUsername를 구현할 때, 완벽한 테스트를 만들고 구현하진 못했음.

추가 테스트

```java
@Test//(expected = UsernameNotFoundException.class) junit4
public void findByUsernameFail() {
    //junit5 version
    //username을 불러오려다 실패해서 예외가 발생하는 테스트를 추가해야 해
    String username = "random@name.com";

    Exception exception = assertThrows(UsernameNotFoundException.class, () -> {
        accountService.loadUserByUsername(username);
    });

    assertThat(exception.getMessage()).contains(username);
}
```

근데 이렇게 하면 예외 타입밖에 확인을 못함.

```java
@Test
public void findByUsernameFail() {
    //username을 불러오려다 실패해서 예외가 발생하는 테스트를 추가해야 해
    String username = "random@name.com";

    try {
        accountService.loadUserByUsername(username);
        fail("supposed to be failed"); //여기 오면 테스트 실패하게 만드는거야.
    } catch (UsernameNotFoundException e) {
        assertThat(e instanceof UsernameNotFoundException).isTrue(); //이 타입으로 받았으니 당연히 맞고,
        assertThat(e.getMessage()).containsSequence(username);
        //에러객체를 받아오기 때문에 더 많은 것을 확인할 수 있음. 단, 코드가 장황해짐.
    }
}
```

@Rule ExpectedException , junit4 제공, junit5에는 더 이상 지원하지 않음.

```java
@Rule
public ExpectedException expectedException = ExpectedException.none();

@Test
public void findByUsernameFile() {
    // Expected
    String username = "random@name.com";
    expectedException.expect(UsernameNotFoundException.class);   //발생할 예외를 미리 적어줘야 함.
    expectedException.expectMessage(Matchers.containsString(username));
    
    // When
    accountService.loadUserByUsername(username);
}
```

https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4-rule-support 변경된 부분 공부



